language: node_js
node_js:
   - "14"
script:
   - npm run build -- $TRAVIS_BUILD_NUMBER
   - npm test
after_success:
   - chrome-webstore-manager update -t $(chrome-webstore-manager refresh_token --client_id $CLIENT_ID --client_secret $CLIENT_SECRET --refresh_token $REFRESH_TOKEN) $EXTENSION_ID ./build/JustDoIt.zip
